dist: bionic

language: php

cache:
    directories:
        - vendor
        - ~/.composer/cache/files

env:
    global:
        - COMPOSER_MEMORY_LIMIT=-1

matrix:
    fast_finish: true
    include:
        # Test the latest stable release
        - php: 7.3
        - php: 7.4

before_install:
    - phpenv config-rm xdebug.ini
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install --no-interaction --prefer-dist

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - bin/php-cs-fixer fix --verbose --diff --dry-run lib/
